# Generated by Django 3.2.15 on 2022-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0002_auto_20220922_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaicsConcordance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
