# Generated by Django 3.2.15 on 2022-10-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0003_naicsconcordance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_value', models.CharField(default='', max_length=255)),
                ('import_value', models.CharField(default='', max_length=255)),
                ('year', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeographyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(default='', max_length=255)),
                ('fips_code', models.CharField(default='', max_length=255)),
                ('geo_id', models.CharField(default='', max_length=255)),
                ('county', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='USA', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeographyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=255)),
                ('meta_details', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeographyPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(default='', max_length=255)),
                ('port_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeographyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=255)),
                ('state_abbreviation', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=255)),
                ('product_code_detail', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='NaicsConcordance',
        ),
        migrations.RemoveField(
            model_name='naicsestablishmentsstate',
            name='naics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='importing_firms_naics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_naics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_codes',
        ),
        migrations.DeleteModel(
            name='Naics',
        ),
        migrations.DeleteModel(
            name='NaicsEstablishmentsState',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCode',
        ),
        migrations.AddField(
            model_name='productcodedetail',
            name='product_code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.productcodetype'),
        ),
        migrations.AddField(
            model_name='geographydetail',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.geographylevel'),
        ),
        migrations.AddField(
            model_name='geographydetail',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.geographyport'),
        ),
        migrations.AddField(
            model_name='geographydetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.geographystate'),
        ),
        migrations.AddField(
            model_name='foreigntrade',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.geographydetail'),
        ),
        migrations.AddField(
            model_name='foreigntrade',
            name='product_code_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.productcodedetail'),
        ),
    ]
