# Generated by Django 3.2.15 on 2022-11-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0004_auto_20221020_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigntrade',
            name='year',
        ),
        migrations.RemoveField(
            model_name='productcodedetail',
            name='product_code_detail',
        ),
        migrations.RemoveField(
            model_name='productcodedetail',
            name='product_name',
        ),
        migrations.AddField(
            model_name='foreigntrade',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foreigntrade',
            name='datetime_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productcodedetail',
            name='product_code_level',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='foreigntrade',
            name='export_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='foreigntrade',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scip.geographydetail'),
        ),
        migrations.AlterField(
            model_name='foreigntrade',
            name='import_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='foreigntrade',
            name='product_code_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scip.productcodedetail'),
        ),
        migrations.AlterField(
            model_name='geographydetail',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scip.geographyport'),
        ),
        migrations.AlterField(
            model_name='geographydetail',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scip.geographystate'),
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=255)),
                ('product_code', models.CharField(default='', max_length=255)),
                ('product_code_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scip.productcodedetail')),
            ],
        ),
    ]
