# Generated by Django 3.2.15 on 2022-11-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0007_auto_20221107_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntrade',
            name='product_code_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scip.productcode'),
        ),
    ]
