# Generated by Django 3.2.15 on 2022-11-23 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0008_alter_foreigntrade_product_code_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcode',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productcode',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.CreateModel(
            name='ProductCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.ManyToManyField(to='scip.ProductCode')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCodeCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code_x', models.ManyToManyField(related_name='product_code_x', to='scip.ProductCode')),
                ('product_code_y', models.ManyToManyField(related_name='product_code_y', to='scip.ProductCode')),
            ],
        ),
    ]
