# Generated by Django 3.2.15 on 2022-12-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0011_auto_20221201_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcodecrosswalk',
            name='product_code_x',
        ),
        migrations.AddField(
            model_name='productcodecrosswalk',
            name='product_code_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_code_x', to='scip.productcode'),
        ),
        migrations.RemoveField(
            model_name='productcodecrosswalk',
            name='product_code_y',
        ),
        migrations.AddField(
            model_name='productcodecrosswalk',
            name='product_code_y',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_code_y', to='scip.productcode'),
        ),
    ]
