# Generated by Django 3.2.15 on 2023-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0013_auto_20230119_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoid',
            name='port',
            field=models.CharField(default='', max_length=255),
        ),
    ]
