# Generated by Django 3.2.15 on 2023-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0014_geoid_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoid',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
