# Generated by Django 3.2.15 on 2022-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scip', '0006_foreigntrade_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreigntrade',
            name='datetime',
        ),
        migrations.AddField(
            model_name='foreigntrade',
            name='month',
            field=models.CharField(default='', max_length=255),
        ),
    ]
